# Generated by Django 3.1 on 2020-08-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(
                default='media\\images\\default.png', upload_to='images/'
            ),
        ),
    ]
