# Generated by Django 3.1 on 2020-08-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200820_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttag',
            name='color',
            field=models.CharField(default='#FFC0CB', max_length=10),
        ),
    ]
