# Generated by Django 3.1 on 2020-08-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200820_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['priority']},
        ),
    ]
