# Generated by Django 3.1 on 2020-08-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200821_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-priority']},
        ),
    ]
