# Generated by Django 3.1 on 2020-08-27 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200821_0959'),
    ]

    operations = [
        migrations.RemoveField(model_name='project', name='links',),
        migrations.AddField(
            model_name='projectlink',
            name='project',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='projects.project',
            ),
        ),
    ]
