name: Docker Image CI

on:
  push:
    branches: 
      - master
      - feature/*

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file docker-compose.test.yml
